apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: backstage-backend-certificate
  namespace: backstage
  labels:
    application: backstage
    component: backend
    environment: poc
    team: breu
spec:
  domains:
    - backend.hd.dev.breu.io
