apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: backstage-backend-frontend
  namespace: backstage
  labels:
    application: backstage
    component: backend
    environment: poc
    team: breu
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
