apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backstage-backend-hpa
  namespace: backstage
  labels:
    application: backstage
    component: backend
    environment: poc
    team: breu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backstage-backend-deployment
  minReplicas: 3
  maxReplicas: 128
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
        # target:
        #   type: AverageValue
        #   averageValue: 384Mi
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # scale down slowly
      policies:
        - type: Percent
          value: 200 # Half of the pods are scaled down
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 10 # scale up quickly
      policies:
        - type: Percent
          value: 400 # 4 x the pods are scaled up
          periodSeconds: 5
      selectPolicy: Max
