apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage
spec:
  targets:
    - ./packages/app/catalog-info.yaml
    - ./packages/backend/catalog-info.yaml
    - ./infra/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
spec:
  owner: breu-dev
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: breu
  description: Breu | Technology for humans
spec:
  type: team
  profile:
    displayName: HD Team @ Breu
    email: hd@breu.io
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: github-rest-api
  description: The official Spotify REST API
spec:
  type: openapi
  lifecycle: production
  owner: breu-dev
  system: backstage/backstage
  definition:
    $text: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.4/ghes-3.4.yaml