version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: backstage/backend
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
    networks:
      - backstage-network
    restart: always
    ports:
      - 7007:7007
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:  # this is the default
      - backstage-db-data:/var/lib/postgresql/data
    networks:
      - backstage-network
    restart: always

networks:
  backstage-network: {}

volumes:
  backstage-db-data: {}