apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web
  title: Backstage Website
  description: Backstage Website
  annotations: {}
  tags: 
    - typescript
    - website
spec:
  type: website
  dependsOn:
    - component:backend
  owner: breu-dev
  lifecycle: poc
  system: backstage