apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  title: Backend for Backstage
  description: Backend for Backstage
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags: 
    - typescript
    - service
spec:
  type: service
  owner: breu
  lifecycle: poc
  dependsOn:
    - resource:backstage-poc-35e94176
    - resource:backstage-cluster-55f14ee8
    - resource:backstage-backend-certificate
    - resource:loadbalancer
  system: backstage
  providesApis:
    - github-rest-api