apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${backstage__backend__deployment__name}
  namespace: ${backstage__namespace__name}
  labels:
%{ for key, value in backstage__backend__labels ~}
    ${key}: ${value}
%{ endfor ~}
spec:
  replicas: 3
  selector:
    matchLabels:
%{ for key, value in backstage__backend__labels ~}
      ${key}: ${value}
%{ endfor ~}
  template:
    metadata:
      labels:
%{ for key, value in backstage__backend__labels ~}
        ${key}: ${value}
%{ endfor ~}
    spec:
      serviceAccountName: ${backstage__service_account__name}
      imagePullSecrets:
        - name: docker
      containers:
        - name: ${backstage__backend__container__name}
          image: ${backstage__backend__container__image}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "192m"
              memory: "256Mi"
          ports:
            -  containerPort: ${backstage__backend__container__port}
          volumeMounts:
            - name: files
              mountPath: /etc/backstage/files
              readOnly: true
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: db_pass
            - name: APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: app_base_url
            - name: BACKEND_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: backend_base_url
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: gitlab_token
            - name: GITLAB_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: gitlab_discovery_url
            - name: ONELOGIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: onelogin_client_id
            - name: ONELOGIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: onelogin_client_secret
            - name: ONELOGIN_ISSUER
              valueFrom:
                secretKeyRef:
                  name: ${backstage__secret__environment_variables}
                  key: onelogin_issuer
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/backstage/files/service_account.json
      volumes:
        - name: files
          secret:
            secretName: ${backstage__secret__files}
            items:
            - key: service_account_json
              path: service_account.json
